"""add usuario_id to cliente and cliente role

Revision ID: 2a7a20e7d9f6
Revises: ceef19bede39
Create Date: 2026-06-27 21:16:41.876798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7a20e7d9f6'
down_revision: Union[str, Sequence[str], None] = 'ceef19bede39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adicionar o novo enum na tabela RoleUsuario (PostgreSQL)
    op.execute("ALTER TYPE role_usuario ADD VALUE IF NOT EXISTS 'cliente'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('usuario_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_clientes_usuario_id'), 'clientes', ['usuario_id'], unique=True)
    op.create_foreign_key('fk_cliente_usuario', 'clientes', 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_index(op.f('ix_clientes_usuario_id'), table_name='clientes')
    op.drop_column('clientes', 'usuario_id')
    # ### end Alembic commands ###
