"""Initial migration

Revision ID: 32caf9ccb308
Revises: 
Create Date: 2026-06-27 18:55:13.609937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32caf9ccb308'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.create_table('servicos',
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duracao_estimada_horas', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'tecnico', 'atendente', name='role_usuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('visitas',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=False),
    sa.Column('tecnico_id', sa.UUID(), nullable=True),
    sa.Column('data_agendada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_realizada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('agendada', 'em_andamento', 'concluida', 'cancelada', name='status_visita'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('numero_os', sa.String(length=20), nullable=True),
    sa.Column('certificado_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_os')
    )
    op.create_index(op.f('ix_visitas_cliente_id'), 'visitas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_visitas_servico_id'), 'visitas', ['servico_id'], unique=False)
    op.create_index(op.f('ix_visitas_status'), 'visitas', ['status'], unique=False)
    op.create_index(op.f('ix_visitas_tecnico_id'), 'visitas', ['tecnico_id'], unique=False)
    op.create_table('cobrancas',
    sa.Column('visita_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'pago', 'vencido', 'cancelado', name='status_cobranca'), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('dinheiro', 'pix', 'cartao_credito', 'cartao_debito', 'boleto', 'transferencia', name='forma_pagamento'), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cobrancas_status'), 'cobrancas', ['status'], unique=False)
    op.create_index(op.f('ix_cobrancas_visita_id'), 'cobrancas', ['visita_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cobrancas_visita_id'), table_name='cobrancas')
    op.drop_index(op.f('ix_cobrancas_status'), table_name='cobrancas')
    op.drop_table('cobrancas')
    op.drop_index(op.f('ix_visitas_tecnico_id'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_status'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_servico_id'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_cliente_id'), table_name='visitas')
    op.drop_table('visitas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('servicos')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
