"""criar tabela auditoria_logs

Revision ID: 879572a61355
Revises: 2a7a20e7d9f6
Create Date: 2026-07-02 21:03:43.226606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879572a61355'
down_revision: Union[str, Sequence[str], None] = '2a7a20e7d9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_logs',
    sa.Column('usuario_email', sa.String(length=255), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_logs_acao'), 'auditoria_logs', ['acao'], unique=False)
    op.create_index(op.f('ix_auditoria_logs_data_hora'), 'auditoria_logs', ['data_hora'], unique=False)
    op.create_index(op.f('ix_auditoria_logs_entidade'), 'auditoria_logs', ['entidade'], unique=False)
    op.create_index(op.f('ix_auditoria_logs_usuario_email'), 'auditoria_logs', ['usuario_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_logs_usuario_email'), table_name='auditoria_logs')
    op.drop_index(op.f('ix_auditoria_logs_entidade'), table_name='auditoria_logs')
    op.drop_index(op.f('ix_auditoria_logs_data_hora'), table_name='auditoria_logs')
    op.drop_index(op.f('ix_auditoria_logs_acao'), table_name='auditoria_logs')
    op.drop_table('auditoria_logs')
    # ### end Alembic commands ###
