"""refatora campos de endereco do cliente

Revision ID: ceef19bede39
Revises: 32caf9ccb308
Create Date: 2026-06-27 20:12:55.242999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceef19bede39'
down_revision: Union[str, Sequence[str], None] = '32caf9ccb308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('endereco', sa.String(length=255), nullable=True))
    op.drop_column('clientes', 'logradouro')
    op.drop_column('clientes', 'estado')
    op.drop_column('clientes', 'cep')
    op.drop_column('clientes', 'bairro')
    op.drop_column('clientes', 'numero')
    op.drop_column('clientes', 'complemento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('complemento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('numero', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('cep', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('estado', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('logradouro', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('clientes', 'endereco')
    # ### end Alembic commands ###
